import { writeVerifiedGlb } from './write-glb.mjs';
import * as THREE from 'three';
import { loadImage } from '@napi-rs/canvas';
import { buildPavilion } from '../src/model.js';
import { installCanvas, loadPlaqueMap, loadMaterialImages } from './node-canvas.mjs';
import { captureScene, exportScene } from '../src/export-scene.js';
import { createExportContext } from '../src/scene-context.js';

installCanvas();
const model = buildPavilion({ plaqueMap: await loadPlaqueMap(), surfaceImages: await loadMaterialImages() });
const normalMap = new THREE.Texture(await loadImage(new URL('../public/textures/water-normal-1.jpg', import.meta.url)));
normalMap.wrapS = normalMap.wrapT = THREE.RepeatWrapping;
const time = 2.3;
model.update(time);
const profile = process.argv.includes('--compatible') ? 'compatible' : 'compact';
const modelOnly = process.argv.includes('--model-only');
const context = createExportContext(model, { time, normalMap });
const snapshot = captureScene(model.root, { ...context, includeContext: !modelOnly });
const binary = await exportScene(snapshot, { profile });
const filename = modelOnly ? 'changyi-pavilion-model.glb' : profile === 'compatible' ? 'changyi-pavilion-compatible.glb' : 'changyi-pavilion.glb';
await writeVerifiedGlb(new URL(`../${filename}`, import.meta.url), new Uint8Array(binary));
console.log(`Exported ${filename} (${(binary.byteLength / 1048576).toFixed(2)} MiB)`);
console.log(JSON.stringify(model.root.userData.geometryMetrics, null, 2));
